Add `play playlist` command
estiens/jukebot pull request #8
Opened 2020-01-18 16:26 UTC by ryansch

Use case: A user already has a playlist link/uri from browsing their own spotify account. They want to command the bot to play that playlist.

Usage:
`bot play playlist spotify:playlist:0e1zsySwa4K8yu96GIBVZq`
`bot play playlist https://open.spotify.com/playlist/0e1zsySwa4K8yu96GIBVZq?si=IBUU5MRQR6O5suZFVRyNgQ`

<img width="650" alt="Screen Shot 2020-01-18 at 8 26 04 AM" src="https://user-images.githubusercontent.com/146013/72667003-3267da80-39cc-11ea-9fdb-46c801aadc71.png">

2020-01-18 16:29 UTC, ryansch commented on includes/bot_regex.rb
> +    super("^#{bot_matcher}[\\s]+(?<command>#{values})([\\s]+(?<expression>.*)|)$", Regexp::IGNORECASE | Regexp::MULTILINE)
From https://github.com/slack-ruby/slack-ruby-bot/commit/ee4c57b246acdda17325a1263976a13bca385f3f

2020-01-21 18:45 UTC, estiens requested changes
Great thanks!

One suggestion - can we leave the syntax for `play` the same and simple use playlist <url> for the play list command rather than the more verbose `play music` and `play playlist`

2020-01-30 21:09 UTC, ryansch commented
@estiens Hasn't the `play music` command always been that way? The help spits out `play music` so it never occurred to me to try `play` by itself.

2020-01-30 22:03 UTC, estiens commented
oh, you might be right, it's been so long since I've used this or looked at
the code that I might have the wrong memories! Thanks for the improvements.
I'll pull it down soon and then get merged to master!

On Thu, Jan 30, 2020 at 3:09 PM Ryan Schlesinger <notifications@github.com>
wrote:

> @estiens <https://github.com/estiens> Hasn't the play music command
> always been that way? The help spits out play music so it never occurred
> to me to try play by itself.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/estiens/jukebot/pull/8?email_source=notifications&email_token=AA6WDDEBRFSQSIVYYT6VBNTRAM62DA5CNFSM4KIT3RB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKMSEHY#issuecomment-580461087>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA6WDDH3Q3SXHWPF4EPCLSTRAM62DANCNFSM4KIT3RBQ>
> .
>

2020-04-28 19:33 UTC, merged